<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block \Bss\QuoteExtension\Block\QuoteExtension\Quote\Item\Renderer */
?>
<?php // @codingStandardsIgnoreFile ?>

<?php
$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
/** @var \Bss\QuoteExtension\Helper\CartHidePrice $cartHidePriceHelper */
$cartHidePriceHelper = $this->helper(Bss\QuoteExtension\Helper\CartHidePrice::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$quote = $block->getQuoteExtension();
$blockProd = $block->getProduct();
?>
<tbody class="cart item">
<tr class="heading hide-desktop">
    <td colspan="7">Product</td>
</tr>
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Product')); ?>" class="col item">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()); ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else: ?>
            <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                    ><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= $_formatedOptionValue['full_view']; ?>
                            <?php else: ?>
                                <?= $_formatedOptionValue['value']; ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= $block->escapeHtmlAttr($message['type']); ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif; ?>
        </div>
        <?php $cols = 1; ?>
    </td>

    <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col sku hide-tablet hide-mobile">
        <?= $block->escapeHtml($blockProd->getSku()); ?>
    </td>

    <td data-th="<?= $block->escapeHtml(__('Lead Time')) ?>" class="col leadTime hide-tablet hide-mobile">
        <?= $block->escapeHtml($blockProd->getAttributeText('gpc_lead_time')); ?>
    </td>

    <?php
    if ($item->getProductType() == 'configurable') {
        $parentProductId = $item->getProductId();
        $childProductSku = $item->getSku();
        $canShowPrice = $cartHidePriceHelper->canShowPrice($parentProductId, $childProductSku, $quote);
    } else {
        $canShowPrice = $cartHidePriceHelper->canShowPrice($item->getProductId(), false, $quote);
    }
    ?>
    <?php if ($canShowPrice): ?>
        <?php if ($canApplyMsrp): ?>
            <td class="col msrp hide-tablet hide-mobile" data-th="<?= $block->escapeHtml(__('Unit Price')); ?>">
                    <span class="pricing msrp">
                        <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')); ?></span>
                        <?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
                        <a href="#" class="action help map" id="<?= $block->escapeHtmlAttr($helpLinkId); ?>"
                            <?php
                            $json = '{"addToCart":{"helpLinkId": "#';
                            $json .= $helpLinkId;
                            $json .= '","productName": "';
                            $json .= $product->getName();
                            $json .= '","showAddToCart": false}}';
                            ?>
                           data-mage-init='<?= $block->escapeHtml($json); ?>'>
                            <span><?= $block->escapeHtml(__("What's this?")); ?></span>
                        </a>
                    </span>
                <?php $cols++; ?>
            </td>
        <?php else: ?>
            <td class="col price hide-tablet hide-mobile" data-th="<?= $block->escapeHtml(__('Unit Price')); ?>">
                <?= $block->getUnitPriceHtml($item); ?>
                <?php $cols++; ?>
            </td>
        <?php endif; ?>
    <?php else: ?>
        <td class="col price hide-tablet hide-mobile" data-th="<?= $block->escapeHtml(__('Unit Price')); ?>">
            <?php $cols++; ?>
        </td>
    <?php endif ?>
    <td class="col qty hide-tablet hide-mobile" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
        <div class="field qty">
            <div class="control qty">
                <label for="cart-<?= $block->escapeHtmlAttr($item->getId()); ?>-qty">
                    <span class="label"><?= $block->escapeHtml(__('Qty')); ?></span>
                    <input id="cart-<?= $block->escapeHtmlAttr($item->getId()); ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($item->getId()); ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($item->getSku()); ?>"
                           value="<?= $block->escapeHtmlAttr($block->getQty()); ?>"
                           type="number"
                           size="4"
                           step="any"
                           title="<?= $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </label>
            </div>
        </div>
        <?php $cols++; ?>
    </td>
    <td class="col subtotal hide-tablet hide-mobile" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canShowPrice): ?>
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($item) ?>
            <?php endif; ?>
        <?php endif; ?>
        <?php $cols++; ?>
    </td>

    <td class="col show-tablet">
        <div data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="sku">
            <?= $block->escapeHtml($blockProd->getSku()); ?>
        </div>

        <div data-th="<?= $block->escapeHtml(__('Lead Time')) ?>" class="leadTime">
            <?= $block->escapeHtml($blockProd->getAttributeText('gpc_lead_time')); ?>
        </div>

        <?php
        if ($item->getProductType() == 'configurable') {
            $parentProductId = $item->getProductId();
            $childProductSku = $item->getSku();
            $canShowPrice = $cartHidePriceHelper->canShowPrice($parentProductId, $childProductSku, $quote);
        } else {
            $canShowPrice = $cartHidePriceHelper->canShowPrice($item->getProductId(), false, $quote);
        }
        ?>
        <?php if ($canShowPrice): ?>
            <?php if ($canApplyMsrp): ?>
                <div class="msrp" data-th="<?= $block->escapeHtml(__('Unit Price')); ?>">
                        <span class="pricing msrp">
                            <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')); ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
                            <a href="#" class="action help map" id="<?= $block->escapeHtmlAttr($helpLinkId); ?>"
                                <?php
                                $json = '{"addToCart":{"helpLinkId": "#';
                                $json .= $helpLinkId;
                                $json .= '","productName": "';
                                $json .= $product->getName();
                                $json .= '","showAddToCart": false}}';
                                ?>
                               data-mage-init='<?= $block->escapeHtml($json); ?>'>
                                <span><?= $block->escapeHtml(__("What's this?")); ?></span>
                            </a>
                        </span>
                    <?php $cols++; ?>
                </div>
            <?php else: ?>
                <div class="price" data-th="<?= $block->escapeHtml(__('Unit Price')); ?>">
                    <?= $block->getUnitPriceHtml($item); ?>
                    <?php $cols++; ?>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <div class="price" data-th="<?= $block->escapeHtml(__('Unit Price')); ?>">
                <?php $cols++; ?>
            </div>
        <?php endif ?>
        <div class="qty" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <div class="control qty">
                    <label for="cart-<?= $block->escapeHtmlAttr($item->getId()); ?>-qty">
                        <input id="cart-<?= $block->escapeHtmlAttr($item->getId()); ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($item->getId()); ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($item->getSku()); ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()); ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtml(__('Qty')); ?>"
                               class="input-text qty"
                               maxlength="12"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                    </label>
                </div>
            </div>
            <?php $cols++; ?>
        </div>
        <div class="subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canShowPrice): ?>
                <?php if ($canApplyMsrp): ?>
                    <span class="cart msrp subtotal">--</span>
                <?php else: ?>
                    <?= $block->getRowTotalHtml($item) ?>
                <?php endif; ?>
            <?php endif; ?>
            <?php $cols++; ?>
        </div>
    </td>

    <td class="col actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
        <div class="actions-toolbar">
            <?= /* @NoEscape */ $block->getActions($item); ?>
        </div>
    </td>
</tr>
</tbody>
