<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */
?>
<div class="c-toolbar__limiter field limiter">
    <label class="label" for="limiter">
        <span><?= $block->escapeHtml(__('View:')) ?></span>
    </label>
    <div class="control">
        <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
            <a data-role="limiter" href="#" data-value="<?= /* @escapeNotVerified */ $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                class="selected"<?php endif ?>>
                <?= /* @escapeNotVerified */ $_limit ?>
            </a>
        <?php endforeach; ?>
    </div>
</div>
