<?php
/** @var Magento\Catalog\Block\Product\View $block */
$product   = $block->getProduct();
$type      = $product->getTypeId();
$shortDesc = $product->getShortDescription();

$badges  = [];

if ($product->getResource()->getAttribute('gpc_product_badges')) {
    $badges = explode(', ', $product->getResource()->getAttribute('gpc_product_badges')->getFrontend()->getValue($product));
    $tmp = null;
    $tmp2 = null;
    foreach($badges as $key => $val) {
        if(str_contains(strtolower($val), 'working days')) {
            $tmp = $val;
            unset($badges[$key]);
        }
        if(str_contains(strtolower($val), 'manufactured')) {
            $tmp2 = $val;
            unset($badges[$key]);
        }
    }

    if($tmp2) {
        $badges[] = $tmp2;
    }
    if($tmp) {
        array_unshift($badges, $tmp);
    }

    $badges = array_values($badges);
}

$productImageAttr = $product->getCustomAttribute( 'brand_image' );
if($productImageAttr) {
    $productImage = $this->helper('Magento\Catalog\Helper\Image')
        ->init($product, 'brand_image')
        ->setImageFile($productImageAttr->getValue());
}

$listAttrVal   = $product->getAttributeText('gpc_size_w_x_d_x_h_mm');
$listAttrLabel = '';
$listAttr      = $product->getGpcListAttribute();
$finalListAttr = '';

if($listAttr) {
    $listAttrVal = $product->getAttributeText($listAttr);
    if (!$listAttrVal) {
        $listAttrVal = '';
    } else {
        $listAttrLabel = $product->getResource()->getAttribute($listAttr)->getFrontend()->getLabel();
    }
}

$finalListAttr = $listAttrLabel . ': ' . $listAttrVal;

$leadTime = $product->getAttributeText('gpc_lead_time');
?>

<div class="c-shortdesc">
    <div class="c-shortdesc__top">
        <?php if ($listAttrLabel) : ?>
            <p><?= $finalListAttr; ?></p>
        <?php endif; ?>
    </div>
    <div class="c-shortdesc__actions">
        <?php if ($product->getDescription()): ?>
            <a class="c-shortdesc__actions__more" href="#tab-label-description">Read more</a>
        <?php endif; ?>
        <?php if($product->getGpcProductVideo()): ?>
            <a class="c-shortdesc__actions__demo" href="#prodVideo">Watch the demo</a>
        <?php endif; ?>
    </div>
    <?php if($shortDesc): ?>
        <div class="c-shortdesc__content">
            <?= $shortDesc; ?>
        </div>
    <?php endif; ?>
</div>

<div class="product__sidebar__badges show-mobile hide-desktop">
    <?php if($leadTime): ?>
        <div class="c-leadTime">
            <img src="<?= $block->getViewFileUrl('images/icons/leadTime.svg'); ?>" alt="Delivery" loading="lazy"/>
            <span>Get this in <strong><?= $leadTime; ?></strong></span>
        </div>
    <?php endif; ?>

    <?php if(count($badges) && $badges[0] !== ''): ?>
        <?php foreach($badges as $badge): ?>
            <?php $badgeLabel = strtolower($badge); ?>
            <?= $block->getChildBlock('c-badges-mobile')->addData(['class' => $badgeLabel])->toHtml(); ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<div class="product__sidebar__details show-mobile hide-desktop">
    <div class="product__sidebar__details__left">
        <span class="product__sidebar__sku">SKU: <?= $block->escapeHtml(__($product->getSku())); ?></span>
        <?php if ($product->isAvailable()) :?>
            <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')); ?>">
                <span>Status: <strong><?= $block->escapeHtml(__('In stock')); ?></strong></span>
            </div>
        <?php else :?>
            <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')); ?>">
                <span>Status: <strong><?= $block->escapeHtml(__('Out of stock')); ?></strong></span>
            </div>
        <?php endif; ?>
    </div>
    <div class="product__sidebar__details__right">
        <?php if($productImageAttr && $productImage): ?>
            <img src="<?= $productImage->getUrl(); ?>" alt="<?= $block->escapeHtml(__($product->getName())); ?>"/>
        <?php endif; ?>
    </div>

    <div class="tier-prices">
        <?= $block->getChildBlock('product.price.tier-mobile')->toHtml(); ?>
    </div>
</div>
