<?php
/** @var \Magento\Catalog\Block\Product\View $block */
$product = $block->getProduct();
$video   = $product->getGpcProductVideo();
?>
<?php if($video): ?>
    <div class="c-prodVideo" id="prodVideo">
        <iframe src="<?= $video; ?>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        <span class="c-prodVideo__play"></span>
    </div>
<?php endif; ?>
