<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var Magento\Framework\View\Element\Html\Links $block */ ?>

<div class="block account-nav">
    <div class="content">
        <nav class="account-nav">
            <span class="account-nav__title"><?php echo $block->escapeHtml(__('My Account')); ?></span>

            <ul class="nav items">
                <?php echo $block->getChildHtml(); ?>
            </ul>
        </nav>
    </div>
</div>
