<?php /** @var Magento\Framework\View\Element\Template $block */ ?>

<nav class="c-footer__social" aria-labelledby="footerSocialLinks">
    <h2 class="sr-only" id="footerSocialLinks">Visit our social media</h2>

    <ul class="o-list o-list--aligned">
        <li class="o-list__item">
            <a href="#" class="o-list__link">
                <i aria-hidden="true" title="Facebook" class="fab fa-facebook-f"></i>
                <span class="sr-only">Facebook</span>
            </a>
        </li>
        <li class="o-list__item">
            <a href="#" class="o-list__link">
                <i aria-hidden="true" title="Instagram" class="fab fa-instagram"></i>
                <span class="sr-only">Instagram</span>
            </a>
        </li>
        <li class="o-list__item">
            <a href="#" class="o-list__link">
                <i aria-hidden="true" title="Twitter" class="fab fa-twitter"></i>
                <span class="sr-only">Twitter</span>
            </a>
        </li>
    </ul>
</nav>
