<?php
declare(strict_types=1);
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

use Magento\Cookie\Block\Html\Notices;
use Magento\Cookie\Helper\Cookie;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Opengento\Gdpr\ViewModel\Cookie\NoticeDataProvider;

/** @var Notices $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Cookie $cookieHelper */
$cookieHelper = $block->getData('cookieHelper');
/** @var NoticeDataProvider $noticeDataProvider */
$noticeDataProvider = $block->getData('noticeDataProvider');

$learnMoreUrl = $noticeDataProvider->getLearnMoreUrl() ?: $block->getPrivacyPolicyLink()
?>
<?php
if ($cookieHelper->isCookieRestrictionModeEnabled()): ?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block">
        <div role="document" class="content" tabindex="0">
            <div class="details">
                <?= /* @noEscape */ $noticeDataProvider->getNoticeHtml() ?>
            </div>
            <div class="actions">
                <button id="btn-cookie-allow" class="action allow c-button c-button--primary">
                    <span><?= $block->escapeHtml(__('Allow')) ?></span>
                </button>

                <a id="btn-cookie-learn" class="action allow c-button c-button--secondary" href="<?= $learnMoreUrl; ?>">
                    <span><?= $block->escapeHtml(__('Learn More')) ?></span>
                </a>
            </div>
        </div>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag('display: none;', 'div#notice-cookie-block') ?>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $cookieHelper->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $escaper->escapeJs($block->getUrl('cookie/index/noCookies')) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
