<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="c-contactUs__info">
    <div class="c-contactUs__info__map">
        <iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9980.6456050585!2d-2.4589982!3d51.2897538!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48722867e2646ae7%3A0xee944d1179d35588!2sStorage%20Systems%20Glos%20Ltd!5e0!3m2!1sen!2suk!4v1726051795955!5m2!1sen!2suk" width="100%" height="260" frameborder="0"></iframe>
    </div>
    <div class="c-contactUs__info__content">
        <?= $block->getChildHtml('contact-us-block'); ?>
    </div>
</div>
