<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var Magento\LayeredNavigation\Block\Navigation\State $block */ ?>

<?php $filters = $block->getActiveFilters(); ?>

<?php if (!empty($filters)): ?>
    <div class="filter-current">
        <div class="block-title filter-title">
            <span><?= $block->escapeHtml(__('Applied filters:')) ?></span>
            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear all')) ?></span></a>
                </div>
            <?php endif; ?>
        </div>
        <ul class="items">
            <?php foreach ($filters as $filter): ?>
                <li class="item">
                    <span class="filter-label"><?php echo $block->escapeHtml(__($filter->getName())); ?></span>
                    <span class="filter-value"><?php echo /* @escapeNotVerified */ $block->stripTags($filter->getLabel()); ?></span>
                    <?php
                    $clearLinkUrl      = $filter->getClearLinkUrl();
                    $currentFilterName = $block->escapeHtml(__($filter->getName())) . ' ' . $block->stripTags($filter->getLabel());
                    if ($clearLinkUrl):
                        ?>
                        <a class="action previous" href="<?php echo /* @escapeNotVerified */ $filter->getRemoveUrl(); ?>"
                           title="<?php echo /* @escapeNotVerified */ __('Previous'); ?>">
                            <span><?php echo /* @escapeNotVerified */ __('Previous'); ?></span>
                        </a>
                        <a class="action remove"
                           title="<?php echo $block->escapeHtml($filter->getFilter()->getClearLinkText()); ?>"
                           href="<?php echo /* @escapeNotVerified */ $clearLinkUrl; ?>">
                            <span><?php echo $block->escapeHtml($filter->getFilter()->getClearLinkText()); ?></span>
                        </a>
                    <?php else: ?>
                        <a class="action remove fa" href="<?php echo /* @escapeNotVerified */ $filter->getRemoveUrl(); ?>"
                           title="<?php echo /* @escapeNotVerified */ $block->escapeHtml(__('Remove')) . ' ' . $currentFilterName; ?>">
                            <span><?php echo /* @escapeNotVerified */ __('Remove This Item'); ?></span>
                        </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
