<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var Magento\Framework\View\Element\Template $block */
$blockCSS = $block->getBlockCss();
?>

<?php if ($blockCSS === "account-nav"): ?>
    <a class="account-nav-toggle">My Account</a>
<?php endif; ?>

<div class="block <?php echo /* @escapeNotVerified */ $blockCSS; ?>">
    <div class="title <?php echo /* @escapeNotVerified */ $blockCSS; ?>-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?php echo /* @escapeNotVerified */ $blockCSS; ?>", "selectorsToggleClass": "active"}}'>
        <strong><?= /* @escapeNotVerified */ $block->getBlockTitle() ?></strong>
    </div>
    <div class="content <?php echo /* @escapeNotVerified */ $blockCSS; ?>-content" id="<?php echo /* @escapeNotVerified */ $blockCSS; ?>">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>

<script>
    require([
        'jquery'
    ], function ($) {
        $(function() {
            $('.account-nav-toggle').on('click', function() {
                $('.account-nav').slideToggle();
                $(this).toggleClass('account-nav-toggle--active');
            });
        });
    });
</script>
