<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var Magento\Theme\Block\Html\Header\Logo $block */
$storeName  = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$logoWidth  = $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '';
$logoHeight = $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '';
?>

<a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php echo $storeName; ?>">
    <img src="<?php echo $block->getLogoSrc(); ?>"
            alt="<?php echo $block->getLogoAlt(); ?>"
            <?php echo $logoWidth; ?>
            <?php echo $logoHeight; ?>
    />
</a>
