<?php
/** @var Magento\Framework\View\Element\Template $block */
?>

<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('.accordion > dd').each(function () {
                if (!$(this).text()) {
                    $(this).remove();
                }
            })

            $('.accordion > dt').each(function() {
                const title = $(this).children('a').children('p');
                if (!title.text()) {
                    $(this).remove();
                }
            })

            const allPanels = $('.accordion > dd').hide();

            $('.accordion > dt > a').click(function(e) {
                e.preventDefault();
                e.stopPropagation();

                const $this = $(this);
                const $target =  $this.parent().next();

                if(!$target.hasClass('active')){
                    allPanels.removeClass('active').slideUp();
                    $('.accordion > dt').removeClass('active');
                    $('.accordion > dt a span').text('+');
                    $target.addClass('active').slideDown();
                    $this.parent().addClass('active');
                    $this.children('span').text('-');
                }
            });
        });
    });
</script>
