<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Warbox\Category\Block\AbstractProduct $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $_productCollection = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $_productCollection = $block->getItems();
            $limit = 0;
            $shuffle = 0;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Related products');
            $_productCollection = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Related products');
            $_productCollection = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $_productCollection = $block->getItemCollection();
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $_productCollection = $block->getItems();

            $showWishlist = true;
            $showCompare = false;
            $showCart = true;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $_productCollection = $exist;
        }
    break;

    case 'other':
    break;
}

// Used to use alternative add to cart functionality within _preview.phtml
$recommendedTemplate = true;

$showCartQty = true;
$_product = null;
?>

<?php if ($exist):?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>

        <div class="block-title title">
            <span id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title; ?></span>
        </div>

        <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
            <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                <div class="products list items product-items product-items-carousel" data-mage-init='{ "productCarousel": {} }'>
                    <?php $iterator = 1; ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php $available = ''; ?>

                        <?php if (!$_product->isComposite() && $_product->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_product->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if ($type == 'related' || $type == 'upsell'): ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item" style="display: none;">' : '</div><div class="item product product-item" style="display: none;">' ?>
                        <?php else: ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                        <?php endif; ?>

                        <div class="item product product-item">
                            <div class="product-item-info"
                                 id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>">
                                <?php
                                $class = '';
                                $productImage = $block->getImage($_product, 'category_page_grid');
                                $prodImages = [];
                                $productImageHover = false;
                                $gallery = $_product->getMediaGalleryImages();

                                foreach ($gallery as $image) {
                                    if(isset($image['file']) && $image['file'] !== '') {
                                        $prodImages[] = $block->getCachedGalleryImage($image->getFile(), $_product);
                                    }
                                }

                                if(count($prodImages) > 1) {
                                    $productImageHover = $prodImages[1];
                                }

                                if ($productImageHover) {
                                    $class = 'photo--hover';
                                }

                                $brandUrl = '/media/wysiwyg/brands/';
                                $brand = '';
                                $brandImage = false;
                                if ($_product->getResource()->getAttribute('gpc_brand')) {
                                    $brand = $_product->getResource()->getAttribute('gpc_brand')->getFrontend()->getValue($_product);
                                    $brandImage = $block->findImageByName($brandUrl, strtolower(str_replace(' ', '-', $brand)));
                                }

                                $listAttrVal   = $_product->getAttributeText('gpc_size_w_x_d_x_h_mm');
                                $listAttrLabel = '';
                                $listAttr      = $_product->getGpcListAttribute();

                                if($listAttr) {
                                    $listAttrVal = $_product->getAttributeText($listAttr);
                                    if (!$listAttrVal) {
                                        $listAttrVal = '';
                                    } else {
                                        $listAttrLabel = $_product->getResource()->getAttribute($listAttr)->getFrontend()->getLabel();
                                    }
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                   class="product photo product-item-photo <?= $class; ?>"
                                   tabindex="-1">
                                    <?= $productImage->toHtml() ?>
                                    <?php if ($productImageHover) : ?>
                                        <img src="<?= $productImageHover; ?>" loading="lazy" class="product-item-photo__rollover" alt="<?= $_product->getName(); ?>"/>
                                    <?php endif; ?>
                                    <?php if ($brandImage && $brandImage !== '/media/wysiwyg/brands/.jpg') : ?>
                                        <img src="<?= $brandImage; ?>" class="product-item-photo__brand" alt="<?= $brand; ?>" loading="lazy"/>
                                    <?php endif; ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php $productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?= $escaper->escapeUrl($_product->getProductUrl()); ?>">
                                            <?=/* @noEscape */ $_product->getName(); ?>
                                        </a>
                                    </strong>
                                    <span class="product-item-size">
                                        <?php if ($listAttrLabel): ?>
                                            <?= /* @noEscape */ $listAttrLabel . ': ' . $listAttrVal; ?>
                                        <?php endif; ?>
                                    </span>

                                    <div class="product-item-attrs">
                                        <div class="product-item-attrs__left">
                                            <div class="product-item-price">
                                                <?= /* @noEscape */ $block->getProductPrice($_product); ?>
                                            </div>

                                            <div class="product-item-inner">
                                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()); ?>"
                                                   title="<?= /* @noEscape */ $productNameStripped ?>"
                                                   class="action more c-button c-button--primary"><?= $escaper->escapeHtml(__('More info')); ?></a>
                                            </div>
                                        </div>
                                        <?php
                                        $badges = [];
                                        if ($_product->getResource()->getAttribute('gpc_product_badges')) {
                                            $badges = explode(', ', $_product->getResource()->getAttribute('gpc_product_badges')->getFrontend()->getValue($_product));

                                            $tmp = null;
                                            $tmp2 = null;
                                            foreach($badges as $key => $val) {
                                                if(str_contains(strtolower($val), 'working days')) {
                                                    $tmp = $val;
                                                    unset($badges[$key]);
                                                }
                                                if(str_contains(strtolower($val), 'manufactured')) {
                                                    $tmp2 = $val;
                                                    unset($badges[$key]);
                                                }
                                            }

                                            if($tmp2) {
                                                $badges[] = $tmp2;
                                            }
                                            if($tmp) {
                                                $badges[] = $tmp;
                                            }

                                            $badges = array_values($badges);
                                        }

                                        $leadTime = $_product->getAttributeText('gpc_lead_time');
                                        ?>
                                        <div class="product-item-attrs__right">
                                            <?php if(count($badges) && $badges[0] !== ''): ?>
                                                <?php foreach($badges as $badge): ?>
                                                    <?php if ($badge && is_string($badge)): ?>
                                                        <?php $badgeBlock = $block->getChildBlock('c-badges-related'); ?>
                                                        <?php if($badgeBlock) : ?>
                                                            <?= $badgeBlock->addData(['class' => $badge])->toHtml(); ?>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>

                                            <?php if($leadTime): ?>
                                                <div class="c-leadTime">
                                                    <img src="<?= $block->getViewFileUrl('images/icons/leadTime.svg'); ?>" alt="Delivery" loading="lazy"/>
                                                    <span>Get this in <strong><?= $leadTime; ?></strong></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <?= ($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>

    <?php if (!$block->isRedirectToCartEnabled() && $_product):?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif;?>

    <?php if ($showCartQty): ?>
        <script>
            require([
                'jquery',
                'stepper',
            ], function($, stepper){
                $(function() {
                    $('.js-qty').stepper({
                        countBy: 1
                    });
                });
            });
        </script>
    <?php endif; ?>
<?php endif;?>
