<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<style>
    .page-main {
        height: 100vh;
        position: relative;
    }
    .c-maintenance {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate3d(-50%,-50%,0);
        text-align: center;
        max-width: 80%;
        width: 100%;

        img {
            width: 500px;
            max-width: 100%;
            height: auto;
        }

        h1 {
            margin-top: 20px;
        }

        p {
            margin: 0;

            a {
                color: #61ac46;
                text-decoration: underline;
            }
        }

        > div {
            margin-top: 20px;
        }
    }

    @media screen and (max-width: 767px) {
        .c-maintenance {
            h1 {
                font-size: 8vw;
            }
        }
    }
</style>

<div class="c-maintenance">
    <img src="images/logo.png" alt="Western Industrial"/>
    <h1>Under Maintenance</h1>
    <p>We're sorry for the inconvenience, but we're performing some maintenance at the moment.</p>
    <p>For anything urgent, you can still contact us at:</p>
    <div>
        <p>Email: <a href="mailto:sales@westernindustrial.co.uk">sales@westernindustrial.co.uk</a></p>
        <p>Phone: <a href="tel:01364651860">01364 651860</a></p>
    </div>
</div>
